### ISSUE TITLE
一运行就报错了 找不到EachNavigationBar/EachNavigationBar-Swift.h    OC 语言

### ISSUE THREAD

**Issue by cocfident** [Pircate/EachNavigationBar#10]
一运行就报错了 找不到EachNavigationBar/EachNavigationBar-Swift.h    OC 语言

**Comment by Pircate** [comment]
请问你的 pod 版本是多少?

**Comment by cocfident** [comment]
1.8.2

**Comment by Pircate** [comment]
我说的是 cocoapods 的版本，我的项目从 1.5.3 升级到 1.6.0 也出现这问题了。新项目用 1.6.0 试了可以。

**Comment by cocfident** [comment]
刚才看了cocoapods的版本是 1.5.3  刚升级了一下 cocoapods  还是不行

**Comment by Pircate** [comment]
你将 <> 改成 "" 试下

**Comment by cocfident** [comment]
是这个 UIViewController+Load.m 里面报错. 不是我引用的时候报错

**Comment by Pircate** [comment]
把 `Podfile.lock` 和 `Pods` 文件夹删了重新 `pod install`，还不行的话等我找到原因告诉你。

**Comment by cocfident** [comment]
还是不行

**Comment by Pircate** [comment]
我去复现了一下找到解决办法了，你的工程应该是 OC 的吧，我将头文件改成这样

<img width="639" alt="default" src="https://user-images.githubusercontent.com/15857442/53248492-d2e84880-36f0-11e9-8330-018aec2551c6.png">

然后随便建了一个空的 `.swift` 文件就不会编译报错了。

**Comment by Pircate** [comment]
你的 `Podfile` 里面是不是没有 `use_frameworks!`，开启这个也可以解决问题。

**Comment by cocfident** [comment]
使用 use_frameworks!  sd的 webp 框架会报找不到头文件的错

**Comment by Pircate** [comment]
那试试另一个方法吧，头文件导入改成这样：

<img width="569" alt="default" src="https://user-images.githubusercontent.com/15857442/53250021-8272ea00-36f4-11e9-9ef3-b1c979a572b3.png">

然后随便添加一个 `.swift` 文件

**Comment by Pircate** [comment]
我是参考了这两篇文章 [使用Pods中使用Swift和Objective-C混编-编译不通过的原因-](https://www.yiem.net/archives/ioskai-fa-shi-yong-podszhong-shi-yong-swifthe-obxjectivechun-bian-bian-yi-bu-tong-guo-de-yuan-yin-ldsymbolsnotfoundforarchitectu.html)

**Comment by cocfident** [comment]
我还是再找找其他修改navbar 高度的框架吧,谢谢了哈,

**Comment by Pircate** [comment]
客气。

**Comment by jezzmemo** [comment]
use_frameworks!不是必须的，所以你要适应开发者是否设置都可以工作，所以这个问题要重视
