### ISSUE TITLE
设置statusBarStyle无效

### ISSUE THREAD

**Issue by qiaqiaxian** [Pircate/EachNavigationBar#12]
navigation.bar.statusBarStyle = .lightContent
这样设置没效果
请问哪里还需要设置呢？

**Comment by Pircate** [comment]
看下有没有哪里设置了导航控制器的导航栏的 `barStyle`

**Comment by qiaqiaxian** [comment]
> 看下有没有哪里设置了导航控制器的导航栏的 `barStyle`

谢谢回复，其他控制器如果设置了的话会影响当前的控制器是吧？

**Comment by Pircate** [comment]
最好都通过我这个来设置，因为代码实现就是通过修改导航控制器的导航栏 `barStyle` 来改变状态栏风格的。

**Comment by qiaqiaxian** [comment]
> 最好都通过我这个来设置，因为代码实现就是通过修改导航控制器的导航栏 `barStyle` 来改变状态栏风格的。

好的，谢谢了，我先修改下。

**Comment by qiaqiaxian** [comment]
> 最好都通过我这个来设置，因为代码实现就是通过修改导航控制器的导航栏 `barStyle` 来改变状态栏风格的。

谢谢提醒，检查了下override了导航栏的preferredStatusBarStyle。
现在能修改了。
顺便谢谢兄弟的轮子，很方便，希望能够一直维护。
