### ISSUE TITLE
Xcode10.3 编译失败，navigation_back_default这张图缺少2x资源

### ISSUE THREAD

**Issue by cwh1992** [Pircate/EachNavigationBar#13]
![14_51_57__07_24_2019](https://user-images.githubusercontent.com/10607882/61771516-a1e87d00-ae22-11e9-8012-a40f68316ae1.jpg)
![14_51_38__07_24_2019](https://user-images.githubusercontent.com/10607882/61771534-ac0a7b80-ae22-11e9-8aed-020297ba3022.jpg)

**Comment by Pircate** [comment]
刚更新的xcode吧，重启电脑能解决。

**Comment by cwh1992** [comment]
> 刚更新的xcode吧，重启电脑能解决。

多谢，重启解决了。
