### ISSUE TITLE
Xcode 11下，用模拟器打开 Demo，右滑返回手势失效！

### ISSUE THREAD

**Issue by NeverAgain11** [Pircate/EachNavigationBar#15]
如题，什么都没改，手势就没用

**Comment by Pircate** [comment]
> 如题，什么都没改，手势就没用

是最新代码吗？我刚刚试了下xcode11+iOS13可以右划返回。

**Comment by Pircate** [comment]
> 如题，什么都没改，手势就没用

只是手势触发在很边缘

**Comment by Pircate** [comment]
![2019-09-21 14 35 54](https://user-images.githubusercontent.com/15857442/65369270-75fc4300-dc7d-11e9-824f-0f32fd1745f8.gif)

**Comment by NeverAgain11** [comment]
不好意思。我一直在屏幕内触发手势的，原来 iOS 13 模拟器竟然需要在屏幕外才能触发。
