### ISSUE TITLE
为什么取消了nav.navigation.configuration.backBarButtonItem？

### ISSUE THREAD

**Issue by gongxiaokai** [Pircate/EachNavigationBar#17]
之前用nav.navigation.configuration.backBarButtonItem  全局配置nav的返回按钮为一个图片。
现在取消了这个特性，要在每一个vc中添加。。。能再加上么。。

**Comment by Pircate** [comment]
由于 iOS 12 之后不能 copy UIBarButtonItem，导致每个 vc 共享一个 backItem，点击返回按钮所有 vc 的 backItem 的 action 会同时调用。

**Comment by gongxiaokai** [comment]
@Pircate 那现在就必须一个一个加吗？有没有什么解决方案吗？

**Comment by Pircate** [comment]
现在只能 basevc 里面加

**Comment by gongxiaokai** [comment]
@Pircate  好的，非常感谢。

**Comment by Pircate** [comment]
更新了一个新版本，加回了全局返回按钮。

```swift
nav.navigation.configuration.backItem = Configuration.BackItem(style: .title("返回"))
```

**Comment by gongxiaokai** [comment]
太感谢了。又能愉快得玩耍了！！
