### ISSUE TITLE
Use of undeclared type 'UINavigationBarAppearance'

### ISSUE THREAD

**Issue by goktugaral** [Pircate/EachNavigationBar#19]
The example project could not find UINavigationBarAppearance

**Comment by Pircate** [comment]
Please use iOS13+ device or simulater.

**Comment by goktugaral** [comment]
Oops! I miss that, thanks for quick reply :)

**Comment by Pircate** [comment]
It's my fault, I forgot to check the iOS version.

**Comment by goktugaral** [comment]
Can I ask another question if you have time? I used your lib to test it out, great job by the way. But unfortunately my project is still support iOS 10. So we had strange behaviour;

vc1 (with transparent) -> vc2 (non transparent with color)
*  Push vc1 to vc2,
* Pull-to-back vc2 to vc1,
Result;
* vc1 (transparent) and screen goes under translucent Navigation Bar.

did you cross this kind of issue? I will try to add some demo. But if you have opinion, you save me a time.

**Comment by Pircate** [comment]
vc1 navigation.bar.isTranslucent = true & vc2 navigation.bar.isTranslucent = false ?

**Comment by Pircate** [comment]
push not present?

**Comment by goktugaral** [comment]
for both of your question; yes.

**Comment by Pircate** [comment]
Sorry, I can't reproduce this question, Can you provide a Demo?
