### ISSUE TITLE
push下一级隐藏状态栏，然后返回上一级，导航栏高度有问题

### ISSUE THREAD

**Issue by xuhuaping** [Pircate/EachNavigationBar#21]

**Comment by Pircate** [comment]
可以提供一下 iOS 和 iPhone 版本吗? 还有导航栏设置了哪些属性?

**Comment by xuhuaping** [comment]
> 可以提供一下iOS和iPhone版本吗？还有导航栏设置了哪些属性？
版本1.4.1    ios13.2   设置了这些属性，在下一级控制器隐藏了导航栏，返回的时候导航栏高度就改变了
navigation.bar.statusBarStyle = .default
        navigation.bar.barTintColor = .white
        navigation.item.title = " 测试"
        navigation.bar.tintColor = .black
        navigation.bar.titleTextAttributes = [NSAttributedString.Key.foregroundColor:UIColor.black]
        navigation.bar.setTitleAlpha(0)

**Comment by xuhuaping** [comment]
> 可以提供一下 iOS 和 iPhone 版本吗? 还有导航栏设置了哪些属性?

iphoneX系列不会  其他的会

**Comment by Pircate** [comment]
是隐藏了还是设成透明了?

**Comment by xuhuaping** [comment]
> 还是

下一级的 状态栏设置隐藏了，导航栏也设置透明了
 override var prefersStatusBarHidden: Bool {
           return isStatusBarHidden
 }

**Comment by Pircate** [comment]
隐藏了状态栏  导航栏设为透明是吧

我用 iPhone8P iOS13.3 试了下没有复现

请问你有 Demo 吗

**Comment by xuhuaping** [comment]
> iOS13.3

你可以用demo试下，我就是出现第三张的情况
![IMG_3667](https://user-images.githubusercontent.com/18001988/71883596-b8388a00-3171-11ea-9415-190528b43431.JPG)
![IMG_3669](https://user-images.githubusercontent.com/18001988/71883598-ba024d80-3171-11ea-9554-c9bf49e14539.JPG)
![IMG_3668](https://user-images.githubusercontent.com/18001988/71883619-c4244c00-3171-11ea-8577-bcb5f1534c17.JPG)

**Comment by Pircate** [comment]
复现了， 只在 iOS13以上的设备上出现，非常感谢。我来看下如何解决。

**Comment by Pircate** [comment]
最新版 1.14.2 已修复.
