### ISSUE TITLE
additionalHeight in iOS 13 looks different.

### ISSUE THREAD

**Issue by Haeuncs** [Pircate/EachNavigationBar#23]
HI
Thank you for sharing your library.
I tried to use this library, but I found that iOS12 and iOS13 has a different shape.
Do you know how to solve it?

Thanks 🕺🏻

![Simulator Screen Shot - iPhone 8 - 2020-03-26 at 19 15 41](https://user-images.githubusercontent.com/39240556/77635646-38fb6b00-6f96-11ea-90d4-2015cedb372d.png)

![Simulator Screen Shot - iPhone 8 - 2020-03-26 at 19 15 42](https://user-images.githubusercontent.com/39240556/77635661-3ef14c00-6f96-11ea-8da2-c99d29b645a1.png)

**Comment by Pircate** [comment]
Thanks for your feedback，this problem will be fixed in the next version.

**Comment by Pircate** [comment]
It has been fixed. Please update the latest version.

**Comment by Haeuncs** [comment]
it works perfectly fine
Thanks 👍
