### ISSUE TITLE
1.14.4版本 additionalHeight会导致整体偏移

### ISSUE THREAD

**Issue by HANSAFUNC** [Pircate/EachNavigationBar#24]

**Comment by HANSAFUNC** [comment]
.

**Comment by Pircate** [comment]
实际效果就是这样，之前 iOS 13 以后没有整体偏移是 bug。

可以查看这个 issue。
https://github.com/Pircate/EachNavigationBar/issues/23

**Comment by Pircate** [comment]
如果你不想整体偏移可以使用 additionalView。

**Comment by HANSAFUNC** [comment]
Thank you

**Comment by HANSAFUNC** [comment]
additionalHeight设计不应该是由下加高度延长 保持contentview整体frame不变吗？

**Comment by Pircate** [comment]
主要是为了兼容 iOS11 之前的导航栏，iOS11 之前的效果就是这样。
