### ISSUE TITLE
出现两个导航栏怎么处理呀

### ISSUE THREAD

**Issue by a407184508** [Pircate/EachNavigationBar#25]

**Comment by Pircate** [comment]
有demo吗

**Comment by a407184508** [comment]
在项目中，在RxSwift群里看看~ viewdebug

**Comment by LeoAiolia** [comment]
我也出现了，最后发现是自定义了navigationBar.shadowImage = UIImage()导致的

**Comment by Pircate** [comment]
> 我也出现了，最后发现是自定义了navigationBar.shadowImage = UIImage()导致的

他的是 storyboard 导致的，你这个是调用了系统的 navigationBar.

**Comment by a407184508** [comment]
sb的这个可以解决吗，嘻嘻
