### ISSUE TITLE
navigation.titleView 设置宽度无效

### ISSUE THREAD

**Issue by winterrain5** [Pircate/EachNavigationBar#26]
设备系统：iOS12.4.4（iOS13以上展示正常）
相关代码：
self.navigation.item.titleView = searchView
searchView.frame = CGRect(x: 0, y: kNavBarHeight, width: kScreenWidth * 0.84, height: kSearchVHeight)
在searchView重写了：
override var intrinsicContentSize: CGSize {
        return UIView.layoutFittingExpandedSize
 }
宽度无法正常展示

**Comment by Pircate** [comment]
重写 intrinsicContentSize 还不行吗

**Comment by winterrain5** [comment]
> 重写 intrinsicContentSize 还不行吗

<img width="574" alt="image" src="https://user-images.githubusercontent.com/15688369/91251344-ccc3a400-e78d-11ea-8d85-0d7eca8ccf4a.png">
重写后在系统的导航栏上是正常的 （牵扯到另一个问题，为什么有两个导航栏）

<img width="487" alt="image" src="https://user-images.githubusercontent.com/15688369/91251479-21671f00-e78e-11ea-910a-1352fe8c8dd5.png">
这是放在EachNavigationBar上的效果

**Comment by Pircate** [comment]
两个导航栏是设计如此，系统的导航栏被我放到最底层了。

titleView 重写了 intrinsicContentSize 在 iOS 12.4.4 不行，其他 iOS 版本没问题是吗？

**Comment by winterrain5** [comment]
> 两个导航栏是设计如此，系统的导航栏被我放到最底层了。
> 
> titleView 重写了 intrinsicContentSize 在 iOS 12.4.4 不行，其他 iOS 版本没问题是吗？

是的 我的另一台iOS13.6是可以的

**Comment by Pircate** [comment]
> > 两个导航栏是设计如此，系统的导航栏被我放到最底层了。
> > titleView 重写了 intrinsicContentSize 在 iOS 12.4.4 不行，其他 iOS 版本没问题是吗？
> 
> 是的 我的另一台iOS13.6是可以的

我下载个12.4的模拟器来测试一下

**Comment by Pircate** [comment]
我在 12.4 上面测试没有复现，你可以建个 Demo 分别使用系统导航栏和 EachNavigationBar 试一下吗？我这边没有12.4.4的测试机。

**Comment by winterrain5** [comment]
> 我在 12.4 上面测试没有复现，你可以建个 Demo 分别使用系统导航栏和 EachNavigationBar 试一下吗？我这边没有12.4.4的测试机。

好的

**Comment by winterrain5** [comment]
> > 我在 12.4 上面测试没有复现，你可以建个 Demo 分别使用系统导航栏和 EachNavigationBar 试一下吗？我这边没有12.4.4的测试机。
> 
> 好的

首先表示感谢，耽误你这么长时间！
说下结果：
我另起了一个新项目，在12.4.4上使用EachNavigationBar也并未发生宽度无法设置的情况（自定义的TitleView和项目保持一致）。
在我自己的项目中，我调整了布局代码到init(frame: CGRect)后，展示就是正常了（之前是在layoutSubView中）。
