### ISSUE TITLE
edgesForExtendedLayout

### ISSUE THREAD

**Issue by philCc** [Pircate/EachNavigationBar#27]
貌似不支持`self.edgesForExtendedLayout = []`

```swift
// NextViewController.swift
    override func viewDidLoad() {
        super.viewDidLoad()

        view.backgroundColor = UIColor.white
        view.addSubview(scrollView)
        view.addSubview(tipLabel)
        
        navigation.item.title = "Next"
        navigation.bar.tintColor = nil
        
        let titleView = UITextField(frame: CGRect(x: 0, y: 0, width: view.bounds.width - 100, height: 30))
        titleView.backgroundColor = UIColor.lightGray
        titleView.layer.cornerRadius = 15
        titleView.layer.masksToBounds = true
        navigation.item.titleView = titleView
        self.edgesForExtendedLayout = []
        if #available(iOS 11.0, *) {
            navigation.bar.prefersLargeTitles = false
        }
        
        navigation.bar.backBarButtonItem?.shouldBack = { item in
            let alert = UIAlertController(title: "确定退出", message: nil, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "取消", style: .cancel, handler: nil))
            alert.addAction(UIAlertAction(title: "确定", style: .default) { _ in
                item.goBack()
            })
            self.present(alert, animated: true, completion: nil)
            debugPrint("shouldBack")
            return false
        }
    }
```

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-08 at 10 44 03](https://user-images.githubusercontent.com/626401/92427874-38f7cc00-f1c0-11ea-848e-87688244292c.png)

**Comment by Pircate** [comment]
确实没有考虑到这个属性的设置，请问你是有什么需求呢？

**Comment by philCc** [comment]
个人主页，需要tableview header悬浮的需求

![WX20200908-123725](https://user-images.githubusercontent.com/626401/92433570-140b5500-f1d0-11ea-8a13-0af5eeb2acce.png)
![WX20200908-123712](https://user-images.githubusercontent.com/626401/92433580-1a013600-f1d0-11ea-96fd-56ee82aed709.png)

**Comment by Pircate** [comment]
头像从导航栏移到header上?

**Comment by philCc** [comment]
头像移动到导航栏是比较简单的，
我的需要是，tableView上滑时，header要悬浮在导航栏下面
![image](https://user-images.githubusercontent.com/626401/92459192-f3a3c080-f1f8-11ea-94a9-0c8f34c7b394.png)
![image](https://user-images.githubusercontent.com/626401/92459388-35cd0200-f1f9-11ea-8658-00b69aabd2c1.png)

**Comment by Pircate** [comment]
懂了，这个tableview的style设置为plain不就支持了吗

**Comment by philCc** [comment]
你说的这个肯定是要设置的啊
现在的问题是，导航栏设置了透明，如果不设置self.edgesForExtendedLayout = []
那么header的悬浮到状态栏的最顶部，转换成全局坐标就是(0,0)，而不是紧贴着导航栏
我要的结果是，上滑后紧贴着导航栏，转换成全局坐标是(0, 状态栏高度+导航栏高度)

**Comment by Pircate** [comment]
导航栏透明你是怎么设置的

**Comment by philCc** [comment]
bar.alpha=0-1啊

**Comment by Pircate** [comment]
现在alpha设为1就可以, 设为0就不行?

**Comment by philCc** [comment]
不设置self.edgesForExtendedLayout = []
![image](https://user-images.githubusercontent.com/626401/92464680-0f5e9500-f200-11ea-8b9f-e2260424a9ea.png)


设置self.edgesForExtendedLayout = []
![image](https://user-images.githubusercontent.com/626401/92464916-6a908780-f200-11ea-89e5-644d5143945d.png)

**Comment by Pircate** [comment]
你tableview顶部是怎么约束的? 不是和导航栏底部约束吗

**Comment by philCc** [comment]
> 现在alpha设为1就可以, 设为0就不行?

如果不改变alpha,那就没问题

**Comment by philCc** [comment]
> 你tableview顶部是怎么约束的? 不是和导航栏底部约束吗

不是啊，如果和导航栏底部约束的话，我tableView上滑以后，headerView上面的按钮不就接收不到点击事件了吗

**Comment by Pircate** [comment]
哥们加个QQ？

**Comment by philCc** [comment]
好的啊，9254792

**Comment by philCc** [comment]
解决方案:
```swift
//self.edgesForExtendedLayout = []
self.tableView.contentInset = UIEdgeInsets(top: barHeight + 40, left: 0, bottom: 0, right: 0)
```
