### ISSUE TITLE
交换方法其实可以不桥接到OC的load方法的

### ISSUE THREAD

**Issue by DarielChen** [Pircate/EachNavigationBar#3]
https://github.com/DarielChen/SwiftTips#26

**Comment by Pircate** [comment]
@DarielChen 这个我看了，可以被覆盖掉。

**Comment by DarielChen** [comment]
什么情况下会被覆盖呢?

**Comment by Pircate** [comment]
@DarielChen extension 优先生效当前模块的, 比如你导入了这个模块, 在你的工程模块也调用了next, 模块内的就失效了.
