### ISSUE TITLE
iPhone12 mini机型EachNavigationBar的Y值和原生的UINavigationBar不一致，其他12机型正常，麻烦大神跟进一下，谢谢

### ISSUE THREAD

**Issue by lm905004880** [Pircate/EachNavigationBar#30]
如题所述：
下面是不同的截图
<img width="770" alt="1605863033716_E0B4FCE2-ADCF-47C1-9C4E-34E549418FC0" src="https://user-images.githubusercontent.com/30647729/99781394-c35e9380-2b52-11eb-92f0-0d4dffc0090c.png">
<img width="784" alt="1605863118307_F0B1A2AC-CC9C-413B-A5EB-0A784E7730DD" src="https://user-images.githubusercontent.com/30647729/99781410-c8234780-2b52-11eb-84ed-7c00611cc664.png">

**Comment by Pircate** [comment]
好的，我晚上看下

**Comment by lm905004880** [comment]
大佬后面有跟进吗？

**Comment by Pircate** [comment]
之前太忙了没有处理，已经修复了

**Comment by lm905004880** [comment]
@Pircate 已解决，谢谢~
