### ISSUE TITLE
Bar Back Item custom(Button) - issue

### ISSUE THREAD

**Issue by jmanalang3** [Pircate/EachNavigationBar#31]
I encounter a weird issue when I am using backItem 
The `navigation.configuration.backItem = .init(style: .custom(backButton))`
after you push 2x to another controller it will show this issue when the user taps on the backItem button (custom)
the navigation pop 2x. this happens when I used ` .init(style: .custom(backButton))` but when i used the `title` and `image` it works fine. also tried to use the completion barkitem `willBack` , `goBack` and `didBack` for the custom to control those weird behavior that I encounter. I believe the button action target calls the number of stacks when the navigation push.

**Comment by Pircate** [comment]
backButton has addTargetAction?

**Comment by jmanalang3** [comment]
Hi Picrate. 

Thank you for the quick response. 
for the backButton there was no `addTargetAction`

`let button = UIButton(type: .system)`
`button.image = "imageName"`
`navigation.configuration.backItem = .init(style: .custom(backButton))`

**Comment by Pircate** [comment]
Sorry, please don't use custom backItem of configuration, It has been removed in the new version. Please use `.init(style: .image())`.

**Comment by jmanalang3** [comment]
Thank you. I saw your changes I was trying to use `.init(style: .custom(backButton)) ` to make my back button reposition inset to align center on my title view because I add extra height on the navigation.

![IMG_5369](https://user-images.githubusercontent.com/11740164/102944352-770dc700-44f5-11eb-933c-c8a68172c0cb.jpg)

**Comment by Pircate** [comment]
`navigation.bar.backBarButtonItem = .init(style: .custom(UIButton()))` 
You can use this in each view controller

**Comment by jmanalang3** [comment]
Yes, that's what I did. Appreciate your effort and you have a cool implementation for this library.
