### ISSUE TITLE
push后导航栏下移

### ISSUE THREAD

**Issue by shunFSKi** [Pircate/EachNavigationBar#4]
你好，请问页面push后导航栏整体下移是为什么

**Comment by Pircate** [comment]
所有页面都这样?

**Comment by shunFSKi** [comment]
是的 push之后就是了，我设了self.extendedLayoutIncludesOpaqueBars = true就OK了，但是我背景色不是透明的啊

**Comment by Pircate** [comment]
> 是的 push之后就是了，我设了self.extendedLayoutIncludesOpaqueBars = true就OK了，但是我背景色不是透明的啊

是不是设了navigationcontroller的navigationbar的属性

**Comment by Pircate** [comment]
还有iOS版本和设备类型可以发一下吗？我复现一下。
