### ISSUE TITLE
隐藏导航栏时的问题

### ISSUE THREAD

**Issue by libern** [Pircate/EachNavigationBar#5]
![image](https://user-images.githubusercontent.com/1830640/51789738-3ac97300-21c7-11e9-89e7-0de0354fa205.png)

**Comment by libern** [comment]
看下左上角

**Comment by Pircate** [comment]
你这个好像没有隐藏掉导航栏

**Comment by Pircate** [comment]
这个页面没有隐藏导航栏，是动态改变导航栏位置。

**Comment by Pircate** [comment]
Demo 已修改
