### ISSUE TITLE
代码出现大量报错信息  不知如何修改 

### ISSUE THREAD

**Issue by Miles-Matheson** [Pircate/EachNavigationBar#57]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/19796675/168779184-ae670d33-c61a-4d41-98b0-8a79b6125ded.png">

**Comment by Pircate** [comment]
我用xcode13试了下是可以编译的

发自我的iPhone

**Comment by Miles-Matheson** [comment]
额  我的xcode13.2.1 编译demo无法通过,通过pod集成也一样报错. 
顺便问下老铁,    \. 这是什么新语法吗  😂

**Comment by Pircate** [comment]
> 额 我的xcode13.2.1 编译demo无法通过,通过pod集成也一样报错. 顺便问下老铁, . 这是什么新语法吗 😂

这是别人提的PR，你的swift版本是多少？

**Comment by Miles-Matheson** [comment]
swift  5.0 用你的demo都跑不起来. 是我xcode版本太低了 难道..?     13.2.1

**Comment by Pircate** [comment]
我的是13.3.1，swift 5.0

**Comment by Miles-Matheson** [comment]
那应该是XCode版本原因了 15年的本子 bigsur只给升到13.2.1 😂

**Comment by Miles-Matheson** [comment]
update xcode last version fix it
