### ISSUE TITLE
支持自动从绑定的控制器获取标题和按钮

### ISSUE THREAD

**Issue by libern** [Pircate/EachNavigationBar#6]
### Storyboard的配置

 ![image](https://user-images.githubusercontent.com/1830640/51790070-aad9f800-21cb-11e9-86a0-6b608cb40373.png)

### 效果

![image](https://user-images.githubusercontent.com/1830640/51790090-d65ce280-21cb-11e9-8df9-c1a1ef0f0161.png)

### 使用EachNavigationBar配置之后

![image](https://user-images.githubusercontent.com/1830640/51790094-e2e13b00-21cb-11e9-8a77-ed841cc30b50.png)

**Comment by Pircate** [comment]
这个下个版本加上

**Comment by Pircate** [comment]
新版已支持

**Comment by libern** [comment]
弱弱问一句，新版啥时候上呀

**Comment by Pircate** [comment]
> 弱弱问一句，新版啥时候上呀

已经发布了，1.6.0版本
