### ISSUE TITLE
返回按钮的位置问题

### ISSUE THREAD

**Issue by libern** [Pircate/EachNavigationBar#7]
这是原生的样子：
![image](https://user-images.githubusercontent.com/1830640/51790535-a7496f80-21d1-11e9-98ec-c28347fede20.png)

这是我尝试想要的：
![image](https://user-images.githubusercontent.com/1830640/51790538-ac0e2380-21d1-11e9-9384-23b6e1f873f8.png)

图片2：
![image](https://user-images.githubusercontent.com/1830640/51790540-af091400-21d1-11e9-872a-56ad4852e79a.png)

可否提供offset设置？并且，内置一个漂亮的图标+文字的返回？

**Comment by Pircate** [comment]
这个主要我也不知道选哪个图标好，所以就交给使用者自定义了

**Comment by Pircate** [comment]
@libern 新版本默认按钮和左右偏移均已支持

**Comment by libern** [comment]
好开心。另外：

如果，你对比一下这个大标题，原生的标题距离左侧的空隙距离貌似，比你这个提供的要距离大一点，你看看。

**Comment by libern** [comment]
我没有仔细读代码，这个是原生实现的，还是模拟还原的？

**Comment by Pircate** [comment]
> 好开心。另外：
> 
> 如果，你对比一下这个大标题，原生的标题距离左侧的空隙距离貌似，比你这个提供的要距离大一点，你看看。

这个应该是因为我设了大标题的字体大小

**Comment by Pircate** [comment]
> 我没有仔细读代码，这个是原生实现的，还是模拟还原的？

模拟的，拿不到原生的图片和标题

**Comment by libern** [comment]
那这个位置偏移会修复吗？

**Comment by Pircate** [comment]
> 那这个位置偏移会修复吗？

暂时不知道原因，后期修复。
