### ISSUE TITLE
Any Plan support Apple Privacy Manifest for cocoapods ? 

### ISSUE THREAD

**Issue by linhaosunny** [Pircate/EachNavigationBar#78]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):

Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library? See the following URLs for additional information:

https://developer.apple.com/news/?id=r1henawx
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by Pircate** [comment]
这个库不在苹果清单里

**Comment by lixiang1994** [comment]
@Pircate 苹果只是列举了一些热门库, 按照要求 所有依赖的第三方库都需要添加隐私清单
