### ISSUE TITLE
无法使用Storyboard的方法

### ISSUE THREAD

**Issue by libern** [Pircate/EachNavigationBar#8]
首先，感谢如此之快的支持。谢谢！

在当前版本1.6.1：
1. 无法触发navigationItem跳转Segue，push下一个controller
2. 无法触发IBAction的方法

![image](https://user-images.githubusercontent.com/1830640/51852916-1524a100-2362-11e9-816c-87d74e7ffb77.png)

**Comment by Pircate** [comment]
这是自定义的导航栏，没有导航栈的，所以不支持

**Comment by libern** [comment]
万分感谢
